language: objective-c

branches:
 only:
 - master

xcode_project: demo/demo.xcworkspace
xcode_scheme: demoTests
osx_image: beta-xcode6.4
xcode_sdk: iphonesimulator

script:
- xctool -workspace demo/demo.xcworkspace -scheme demoTests -sdk iphonesimulator test