use_frameworks!
platform :osx, '10.10'
target 'lib' do
source 'https://github.com/CocoaPods/Specs.git'
pod 'PubNub', '~>4.0'
source 'https://github.com/krzyzanowskim/CryptoSwift'
pod 'CryptoSwift'
end
